// =====================================================
// ACCOMMODATION DEMO SEED DATA
// Phase 2B-2 — Booking Bridge OS
// Source: Supplied handwritten rate sheets
// =====================================================

import type {
  AccommodationProperty,
  RoomCategory,
  RatePeriod,
  RateSupplement,
} from '../types/accommodation';

const NOW = new Date().toISOString();

// =====================================================
// HELPER: Create a standard MAP rate with EB/CWB supplements
// =====================================================
function makeRate(
  id: string,
  propertyId: string,
  roomCategoryId: string,
  baseRate: number,
  ebAmount: number,
  cwbAmount: number | null,
  validFrom: string = '2026-01-01',
  validTo: string | null = null,
  notes?: string
): RatePeriod {
  const supplements: RateSupplement[] = [
    {
      id: `${id}-sup-eb`,
      ratePeriodId: id,
      type: 'EB',
      name: 'Extra Bed',
      amount: ebAmount,
      unit: 'per_room_night',
      taxTreatment: 'NEEDS_CONFIRMATION',
      isDemo: true,
    },
  ];

  if (cwbAmount !== null) {
    supplements.push({
      id: `${id}-sup-cwb`,
      ratePeriodId: id,
      type: 'CWB',
      name: 'Child With Bed',
      amount: cwbAmount,
      unit: 'per_child_night',
      taxTreatment: 'NEEDS_CONFIRMATION',
      isDemo: true,
    });
  }

  return {
    id,
    propertyId,
    roomCategoryId,
    contractType: 'STANDARD',
    mealPlan: 'MAP',
    validFrom,
    validTo,
    baseRate,
    currency: 'INR',
    taxTreatment: 'NEEDS_CONFIRMATION',
    confirmationStatus: 'NEEDS_CONFIRMATION',
    supplements,
    notes,
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    status: 'ACTIVE',
    isDemo: true,
  };
}

// =====================================================
// SRINAGAR PROPERTIES (11)
// =====================================================

export const DEMO_ACCOMMODATION_PROPERTIES: AccommodationProperty[] = [
  // --- Srinagar ---
  {
    id: 'accom-sgr-regal',
    name: 'Regal Palace',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Comfortable hotel in Srinagar offering MAP accommodation with standard amenities.',
    amenities: ['WiFi', 'Room Service', 'Parking'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-sgr-limewood',
    name: 'Lime Wood',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Budget-friendly Srinagar hotel with MAP meal plan and central location.',
    amenities: ['WiFi', 'Restaurant', 'Room Service'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-sgr-lakeavenue',
    name: 'Lake Avenue',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Lakeside hotel in Srinagar with scenic views and MAP accommodation.',
    amenities: ['Lake View', 'WiFi', 'Restaurant', 'Parking'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-sgr-gurcoo',
    name: 'Gurcoo Residency',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Upscale residency hotel offering premium MAP stays in Srinagar.',
    amenities: ['WiFi', 'Restaurant', 'Room Service', 'Parking', 'Garden'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-sgr-frenchwin',
    name: 'French Windows',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Boutique hotel with European-inspired design and MAP meal plan.',
    amenities: ['WiFi', 'Boutique Dining', 'Garden View', 'Parking'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-sgr-kareemgold',
    name: 'Kareem Gold',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Premium Srinagar hotel with seasonal rate structure and MAP accommodation.',
    amenities: ['WiFi', 'Restaurant', 'Room Service', 'Conference Room', 'Parking'],
    preferredProperty: true,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-sgr-kareemresidency',
    name: 'Kareem Residency',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Upscale Srinagar hotel with seasonal MAP rates.',
    amenities: ['WiFi', 'Restaurant', 'Room Service', 'Conference Room', 'Parking'],
    preferredProperty: true,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-sgr-oni',
    name: 'Oni Boutique',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Stylish boutique hotel in Srinagar offering premium MAP stays.',
    amenities: ['WiFi', 'Boutique Design', 'Restaurant', 'Spa', 'Parking'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-sgr-bellmount',
    name: 'Bell Mount',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Well-appointed Srinagar hotel with MAP plan and mountain proximity.',
    amenities: ['WiFi', 'Restaurant', 'Room Service', 'Parking'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-sgr-nagash',
    name: 'Nagash Residency',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Affordable Srinagar residency hotel with MAP accommodation.',
    amenities: ['WiFi', 'Restaurant', 'Room Service'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-sgr-dewannagash',
    name: 'Dewan Nagash',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Premium Srinagar hotel with luxury MAP rates and superior amenities.',
    amenities: ['WiFi', 'Fine Dining', 'Spa', 'Lake View', 'Parking', 'Conference Room'],
    preferredProperty: true,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-sgr-luxheritage',
    name: 'Luxury Heritage',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Heritage-style luxury hotel in Srinagar with MAP meal plan.',
    amenities: ['WiFi', 'Heritage Architecture', 'Garden', 'Restaurant', 'Parking'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },

  // --- Pahalgam (6) ---
  {
    id: 'accom-pah-luxheights',
    name: 'Luxury Heights',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Pahalgam',
    description: 'Budget-friendly Pahalgam hotel with MAP plan and valley views.',
    amenities: ['WiFi', 'Restaurant', 'Valley View', 'Parking'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-pah-goldenheritage',
    name: 'Golden Heritage',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Pahalgam',
    description: 'Heritage-style Pahalgam hotel with MAP accommodation and Lidder river views.',
    amenities: ['WiFi', 'River View', 'Restaurant', 'Garden', 'Parking'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-pah-lidder',
    name: 'Lidder Resort',
    propertyType: 'RESORT',
    location: 'Kashmir',
    city: 'Pahalgam',
    description: 'Riverside resort in Pahalgam offering MAP stays alongside the Lidder river.',
    amenities: ['WiFi', 'River View', 'Restaurant', 'Bonfire Area', 'Parking'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-pah-larida',
    name: 'Larida Resort',
    propertyType: 'RESORT',
    location: 'Kashmir',
    city: 'Pahalgam',
    description: 'Premium Pahalgam resort with MAP meal plan and scenic surroundings.',
    amenities: ['WiFi', 'Restaurant', 'Garden', 'Activity Center', 'Parking'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-pah-ethos',
    name: 'Ethos Pahalgam',
    propertyType: 'HOTEL',
    location: 'Kashmir',
    city: 'Pahalgam',
    description: 'Modern hotel in Pahalgam with MAP accommodation and mountain views.',
    amenities: ['WiFi', 'Mountain View', 'Restaurant', 'Parking'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-pah-sojoom',
    name: 'Sojoom Cottage',
    propertyType: 'HOMESTAY',
    location: 'Kashmir',
    city: 'Pahalgam',
    description: 'Cozy cottage-style stay in Pahalgam with MAP meal plan.',
    amenities: ['WiFi', 'Garden', 'Home-Cooked Meals', 'Mountain View'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },

  // --- Houseboats (5) ---
  {
    id: 'accom-hb-shangrilla',
    name: 'Shangrilla Houseboat',
    propertyType: 'HOUSEBOAT',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Traditional cedar houseboat on Dal/Nigeen Lake with MAP meal plan.',
    amenities: ['Private Sun Deck', 'Kashmiri Cuisine', 'Shikara Access', 'Heating'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-hb-hayat',
    name: 'Hayat Houseboat',
    propertyType: 'HOUSEBOAT',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Mid-range houseboat with MAP accommodation and lake views.',
    amenities: ['Sun Deck', 'Kashmiri Cuisine', 'Shikara Access', 'WiFi'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-hb-shubeena',
    name: 'Shubeena Houseboat',
    propertyType: 'HOUSEBOAT',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Comfortable houseboat stay with MAP plan and traditional décor.',
    amenities: ['Sun Deck', 'Home-Cooked Meals', 'Shikara Access', 'Heating'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-hb-shabnam',
    name: 'Shabnam Houseboat',
    propertyType: 'HOUSEBOAT',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Premium houseboat with luxury MAP stays and walnut wood interiors.',
    amenities: ['Private Sun Deck', 'Butler Service', 'Fine Dining', 'Shikara Access', 'Heating', 'WiFi'],
    preferredProperty: true,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-hb-harmukh',
    name: 'Harmukh Houseboat',
    propertyType: 'HOUSEBOAT',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Ultra-luxury houseboat with premium MAP accommodation and concierge service.',
    amenities: ['Private Sun Deck', 'Butler Service', 'Gourmet Dining', 'Private Shikara', 'Heating', 'WiFi', 'Jacuzzi'],
    preferredProperty: true,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
  {
    id: 'accom-hb-bulbul',
    name: 'Bulbul Houseboat',
    propertyType: 'HOUSEBOAT',
    location: 'Kashmir',
    city: 'Srinagar',
    description: 'Charming houseboat with MAP meal plan.',
    amenities: ['Sun Deck', 'Shikara Access'],
    preferredProperty: false,
    status: 'ACTIVE',
    currency: 'INR',
    photos: [],
    availabilityStatus: 'NOT_CHECKED',
    createdAt: NOW,
    updatedAt: NOW,
    createdBy: 'system',
    isDemo: true,
  },
];

// =====================================================
// ROOM CATEGORIES (1 Deluxe Room per property — initial import)
// =====================================================

export const DEMO_ROOM_CATEGORIES: RoomCategory[] = [
  ...DEMO_ACCOMMODATION_PROPERTIES.filter(p => p.id !== 'accom-sgr-kareemresidency').map(p => ({
    id: `rc-${p.id}`,
    propertyId: p.id,
    name: 'Deluxe Room',
    description: `Standard deluxe room at ${p.name}`,
    maxAdults: 2,
    maxChildren: 1,
    bedConfiguration: p.propertyType === 'HOUSEBOAT' ? '1 Double' : '1 King or Twin',
    amenities: ['Attached Bathroom', 'Hot Water', 'Towels'],
    photos: [],
    active: true,
    sortOrder: 1,
    createdAt: NOW,
    updatedAt: NOW,
    isDemo: true,
  })),
  {
    id: 'rc-accom-sgr-kareemresidency',
    propertyId: 'accom-sgr-kareemresidency',
    name: 'Premium Deluxe',
    description: 'Premium room with MAP meal plan.',
    maxAdults: 3,
    maxChildren: 2,
    bedConfiguration: '1 Double',
    amenities: ['WiFi', 'Room Heater', 'Ensuite Bathroom'],
    photos: [],
    active: true,
    sortOrder: 1,
    createdAt: NOW,
    updatedAt: NOW,
    isDemo: true,
  }
];

// =====================================================
// RATE PERIODS (STANDARD MAP rates from supplied sheets)
// =====================================================

export const DEMO_RATE_PERIODS: RatePeriod[] = [
  // --- Srinagar ---
  makeRate('rate-sgr-regal',        'accom-sgr-regal',       'rc-accom-sgr-regal',       2800, 1000, 800),
  makeRate('rate-sgr-limewood',     'accom-sgr-limewood',    'rc-accom-sgr-limewood',    2800, 1000, 800),
  makeRate('rate-sgr-lakeavenue',   'accom-sgr-lakeavenue',  'rc-accom-sgr-lakeavenue',  3250, 1500, 1200),
  makeRate('rate-sgr-gurcoo',       'accom-sgr-gurcoo',      'rc-accom-sgr-gurcoo',      3500, 1200, 1000),
  makeRate('rate-sgr-frenchwin',    'accom-sgr-frenchwin',   'rc-accom-sgr-frenchwin',   3000, 1200, 1000),
  // Kareem Gold — single rate (not seasonal like Kareem Residency)
  makeRate('rate-sgr-kareemgold',   'accom-sgr-kareemgold',  'rc-accom-sgr-kareemgold',  4500, 1500, 1000),
  makeRate('rate-sgr-oni',          'accom-sgr-oni',         'rc-accom-sgr-oni',         4500, 1500, 1200),
  makeRate('rate-sgr-bellmount',    'accom-sgr-bellmount',   'rc-accom-sgr-bellmount',   3500, 1200, 1000),
  makeRate('rate-sgr-nagash',       'accom-sgr-nagash',      'rc-accom-sgr-nagash',      3000, 1200, 800),
  makeRate('rate-sgr-dewannagash',  'accom-sgr-dewannagash', 'rc-accom-sgr-dewannagash', 6000, 1800, 1500),
  makeRate('rate-sgr-luxheritage',  'accom-sgr-luxheritage', 'rc-accom-sgr-luxheritage', 3500, 1500, 1200),

  // --- Pahalgam ---
  makeRate('rate-pah-luxheights',      'accom-pah-luxheights',      'rc-accom-pah-luxheights',      2000, 800,  600),
  makeRate('rate-pah-goldenheritage',  'accom-pah-goldenheritage',  'rc-accom-pah-goldenheritage',  2500, 1200, 1000),
  makeRate('rate-pah-lidder',          'accom-pah-lidder',          'rc-accom-pah-lidder',          2500, 1000, 800),
  makeRate('rate-pah-larida',          'accom-pah-larida',          'rc-accom-pah-larida',          3000, 1200, 1000),
  makeRate('rate-pah-ethos',           'accom-pah-ethos',           'rc-accom-pah-ethos',           2500, 1000, 800),
  makeRate('rate-pah-sojoom',          'accom-pah-sojoom',          'rc-accom-pah-sojoom',          2500, 800,  600),

  // --- Houseboats ---
  makeRate('rate-hb-shangrilla', 'accom-hb-shangrilla', 'rc-accom-hb-shangrilla', 3000, 800,  600),
  makeRate('rate-hb-hayat',      'accom-hb-hayat',      'rc-accom-hb-hayat',      4000, 1200, 1000),
  makeRate('rate-hb-shubeena',   'accom-hb-shubeena',   'rc-accom-hb-shubeena',   4000, 1000, 800),
  makeRate('rate-hb-shabnam',    'accom-hb-shabnam',     'rc-accom-hb-shabnam',    6000, 2000, 1500),
  makeRate('rate-hb-harmukh',    'accom-hb-harmukh',     'rc-accom-hb-harmukh',    8000, 2000, 1500),

  // --- KAREEM RESIDENCY SEASONAL RATES ---
  makeRate('rp-accom-sgr-kareemresidency-sep', 'accom-sgr-kareemresidency', 'rc-accom-sgr-kareemresidency', 3500, 1200, 800, '2026-09-01', '2026-09-30', 'September Rate'),
  makeRate('rp-accom-sgr-kareemresidency-oct', 'accom-sgr-kareemresidency', 'rc-accom-sgr-kareemresidency', 4000, 1400, 900, '2026-10-01', null, 'October Onwards Rate'),
];
