import { UserRole, RolePermissions } from '../types';

export const ROLE_DEFINITIONS: Record<UserRole, RolePermissions> = {
  Founder: {
    role: 'Founder',
    description: 'Complete unrestricted oversight and administrative execution across all systems, AI tools, finances, and team members.',
    canViewAllSales: true,
    canManageLeads: true,
    canSendQuotes: true,
    canManageMarketing: true,
    canViewFinancials: true,
    canManageOperations: true,
    canManageUsers: true,
    canAccessAiCommand: true,
    canApproveActions: true,
    canViewAuditLogs: true,
    canManageSettings: true,
    canManageTrips: true,
    canManageBookings: true,
    canViewMargins: true,
    leadAccessScope: 'ALL'
  },
  Admin: {
    role: 'Admin',
    description: 'System administration, user access management, CRM configurations, operational data and system security.',
    canViewAllSales: true,
    canManageLeads: true,
    canSendQuotes: true,
    canManageMarketing: true,
    canViewFinancials: true,
    canManageOperations: true,
    canManageUsers: true,
    canAccessAiCommand: true,
    canApproveActions: true,
    canViewAuditLogs: true,
    canManageSettings: true,
    canManageTrips: true,
    canManageBookings: true,
    canViewMargins: true,
    leadAccessScope: 'ALL'
  },
  'Sales Manager': {
    role: 'Sales Manager',
    description: 'Supervise sales pipeline, team lead assignments, quote margins, revenue quotas, and team Sales AI coaching.',
    canViewAllSales: true,
    canManageLeads: true,
    canSendQuotes: true,
    canManageMarketing: false,
    canViewFinancials: true,
    canManageOperations: true,
    canManageUsers: false,
    canAccessAiCommand: true,
    canApproveActions: true,
    canViewAuditLogs: true,
    canManageSettings: false,
    canManageTrips: true,
    canManageBookings: true,
    canViewMargins: true,
    leadAccessScope: 'ALL'
  },
  'Sales Executive': {
    role: 'Sales Executive',
    description: 'Direct customer engagement, lead follow-ups, quotation creation, chat handling, and individual Sales AI assistant.',
    canViewAllSales: false,
    canManageLeads: true,
    canSendQuotes: true,
    canManageMarketing: false,
    canViewFinancials: false,
    canManageOperations: false,
    canManageUsers: false,
    canAccessAiCommand: true,
    canApproveActions: false,
    canViewAuditLogs: false,
    canManageSettings: false,
    canManageTrips: true,
    canManageBookings: true,
    canViewMargins: false,
    leadAccessScope: 'ASSIGNED_ONLY'
  },
  Marketing: {
    role: 'Marketing',
    description: 'Ad campaign management, creative generation, seasonal travel strategy, content calendar, and Marketing AI.',
    canViewAllSales: false,
    canManageLeads: false,
    canSendQuotes: false,
    canManageMarketing: true,
    canViewFinancials: false,
    canManageOperations: false,
    canManageUsers: false,
    canAccessAiCommand: true,
    canApproveActions: false,
    canViewAuditLogs: true,
    canManageSettings: false,
    canManageTrips: false,
    canManageBookings: false,
    canViewMargins: false,
    leadAccessScope: 'NONE'
  },
  Operations: {
    role: 'Operations',
    description: 'Ground transport logistics, hotel allocations, houseboat bookings, chauffeur coordination, and guest on-tour safety.',
    canViewAllSales: false,
    canManageLeads: false,
    canSendQuotes: false,
    canManageMarketing: false,
    canViewFinancials: false,
    canManageOperations: true,
    canManageUsers: false,
    canAccessAiCommand: true,
    canApproveActions: false,
    canViewAuditLogs: true,
    canManageSettings: false,
    canManageTrips: false,
    canManageBookings: true,
    canViewMargins: false,
    leadAccessScope: 'NONE'
  },
  Accounts: {
    role: 'Accounts',
    description: 'Financial ledger, customer balance clearances, supplier/hotel disbursements, GST invoicing, and margin audits.',
    canViewAllSales: true,
    canManageLeads: false,
    canSendQuotes: false,
    canManageMarketing: false,
    canViewFinancials: true,
    canManageOperations: false,
    canManageUsers: false,
    canAccessAiCommand: true,
    canApproveActions: true,
    canViewAuditLogs: true,
    canManageSettings: false,
    canManageTrips: false,
    canManageBookings: true,
    canViewMargins: true,
    leadAccessScope: 'ALL'
  }
};

export const PRESET_USERS = [
  {
    id: 'emp-founder-01',
    name: 'Suhaib Hamid',
    email: 'suhaib@bookingbridge.com',
    phone: '+91 94190 00001',
    role: 'Founder' as UserRole,
    department: 'Executive Leadership',
    active: true,
    createdAt: '2025-01-01T00:00:00Z',
    lastLogin: new Date().toISOString()
  },
  {
    id: 'emp-admin-01',
    name: 'Nasir Wani',
    email: 'nasir.admin@bookingbridge.com',
    phone: '+91 94190 00002',
    role: 'Admin' as UserRole,
    department: 'Operations & IT',
    active: true,
    createdAt: '2025-01-05T00:00:00Z',
    lastLogin: new Date().toISOString()
  },
  {
    id: 'emp-mgr-01',
    name: 'Sameer Mir',
    email: 'sameer.sales@bookingbridge.com',
    phone: '+91 94190 00003',
    role: 'Sales Manager' as UserRole,
    department: 'Sales & Revenue',
    active: true,
    createdAt: '2025-01-10T00:00:00Z',
    lastLogin: new Date().toISOString()
  },
  {
    id: 'emp-sales-01',
    name: 'Tariq Bhat',
    email: 'tariq.sales@bookingbridge.com',
    phone: '+91 94190 00004',
    role: 'Sales Executive' as UserRole,
    department: 'Sales & Inbound',
    active: true,
    createdAt: '2025-02-01T00:00:00Z',
    lastLogin: new Date().toISOString()
  },
  {
    id: 'emp-sales-02',
    name: 'Ayesha Zargar',
    email: 'ayesha.sales@bookingbridge.com',
    phone: '+91 94190 00005',
    role: 'Sales Executive' as UserRole,
    department: 'Sales & Luxury Packages',
    active: true,
    createdAt: '2025-02-15T00:00:00Z',
    lastLogin: new Date().toISOString()
  },
  {
    id: 'emp-mkt-01',
    name: 'Irfan Dar',
    email: 'irfan.mkt@bookingbridge.com',
    phone: '+91 94190 00006',
    role: 'Marketing' as UserRole,
    department: 'Growth & Social Strategy',
    active: true,
    createdAt: '2025-02-20T00:00:00Z',
    lastLogin: new Date().toISOString()
  },
  {
    id: 'emp-ops-01',
    name: 'Bilal Ahmad Shah',
    email: 'bilal.ops@bookingbridge.com',
    phone: '+91 94190 00007',
    role: 'Operations' as UserRole,
    department: 'Ground Fleet & Stays Logistics',
    active: true,
    createdAt: '2025-02-25T00:00:00Z',
    lastLogin: new Date().toISOString()
  },
  {
    id: 'emp-acc-01',
    name: 'Farooq Lone',
    email: 'farooq.accounts@bookingbridge.com',
    phone: '+91 94190 00008',
    role: 'Accounts' as UserRole,
    department: 'Finance & Compliance',
    active: true,
    createdAt: '2025-03-01T00:00:00Z',
    lastLogin: new Date().toISOString()
  }
];
